env:
    browser: true
    es2020: true
globals:
    chrome: readonly
extends:
    - airbnb-base
    - plugin:prettier/recommended
parserOptions:
    ecmaVersion: 2020
    sourceType: script
rules:
    import/extensions: [error, ignorePackages]
    import/no-extraneous-dependencies: [error, { packageDir: '.' }]
    strict: [error, global]
