env:
  browser: true
  es2020: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  import/extensions: [error, ignorePackages]
  import/no-extraneous-dependencies: [error, { packageDir: "." }]
